Repository simonw/llm, pull requests merged in 2023-09, with the labels that each got.

#257 Updated error message for invalid or missing embedding model
  llm/cli.py
  tests/test_embed_cli.py
Labels: developer-experience

#263 change type of cli "embed -c" to be STR not FILE
  docs/help.md
  llm/cli.py
Labels: bug

#254 Binary embeddings
  docs/embeddings/python-api.md
  docs/help.md
  llm/cli.py
  llm/default_plugins/openai_models.py
  llm/embeddings.py
  llm/embeddings_migrations.py
  llm/models.py
  tests/conftest.py
  tests/test_embed.py
  tests/test_embed_cli.py
  tests/test_migrate.py
Labels: enhancement, embeddings
