Repository simonw/llm, pull requests merged in 2025-03, with the labels that each got.

#819 Add supports_schema to extra-openai-models.yaml
  docs/other-models.md
  llm/default_plugins/openai_models.py
Labels: enhancement, schemas

#843 Support vision and audio for extra-openai-models.yaml
  docs/other-models.md
  llm/default_plugins/openai_models.py
Labels: openai

#845 Ability to store options in templates
  docs/templates.md
  llm/cli.py
  llm/templates.py
  tests/test_templates.py
Labels: enhancement

#846 options family of commands for setting default options
  docs/help.md
  docs/usage.md
  llm/cli.py
  tests/test_cli_options.py
Labels: enhancement
