Repository simonw/llm, pull requests merged in 2025-04, with the labels that each got.

#859 Fragments
  docs/help.md
  docs/logging.md
  docs/python-api.md
  docs/usage.md
  llm/cli.py
  llm/migrations.py
  llm/models.py
  llm/templates.py
  llm/utils.py
  setup.py
  tests/test_fragments_cli.py
  tests/test_llm.py
  tests/test_llm_logs.py
  tests/test_templates.py
Labels: enhancement, fragments

#877 Update OpenAI model command to include API key and environment variables
  docs/usage.md
  llm/cli.py
  tests/test_aliases.py
  tests/test_llm.py
Labels: enhancement, developer-experience

#876 Allow escaping a dollar sign in templates by adding another dollar sign
  docs/templates.md
  llm/templates.py
  tests/test_templates.py
Labels: bug, templates

#908 Convert from setup.py to pyproject.toml
  .github/workflows/test.yml
  docs/contributing.md
  pyproject.toml
  setup.py
Labels: enhancement

#909 py.typed marker file
  llm/py.typed
Labels: developer-experience
