Repository simonw/llm, pull requests merged in 2025-02, with the labels that each got.

#737 llm logs --prompts option
  docs/help.md
  docs/logging.md
  llm/cli.py
  tests/test_llm.py
Labels: enhancement

#753 KeyModel and AsyncKeyModel classes for models that taken keys
  docs/plugins/advanced-model-plugins.md
  docs/plugins/tutorial-model-plugin.md
  docs/python-api.md
  llm/__init__.py
  llm/cli.py
  llm/default_plugins/openai_models.py
  llm/models.py
  tests/conftest.py
  tests/test_llm.py
Labels: enhancement, design, asyncio

#775 Upgrade to Pydantic v2
  .github/workflows/test.yml
  llm/cli.py
  llm/default_plugins/openai_models.py
  llm/models.py
  llm/templates.py
  pytest.ini
  setup.py
Labels: dependencies

#774 Add note about similarity function in "similar" command's doc
  docs/embeddings/cli.md
  docs/help.md
  llm/cli.py
Labels: documentation

#777 llm prompt --schema X option and model.prompt(..., schema=) parameter
  docs/changelog.md
  docs/help.md
  docs/logging.md
  docs/plugins/advanced-model-plugins.md
  docs/python-api.md
  docs/usage.md
  llm/cli.py
  llm/default_plugins/openai_models.py
  llm/migrations.py
  llm/models.py
  tests/conftest.py
  tests/test_chat.py
  tests/test_embed_cli.py
  tests/test_llm.py
  tests/test_migrate.py
Labels: enhancement

#787 Schema template --save --schema support
  docs/templates.md
  docs/usage.md
  llm/cli.py
  llm/templates.py
  tests/test_templates.py
Labels: enhancement, schemas
